sudo: required
services:
  - docker

before_install:
  - docker build -t nickg/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nickg/react-test npm test

after_success:
  - docker build -t nickgigliotos/multi-client ./client
  - docker build -t nickgigliotos/multi-nginx ./nginx
  - docker build -t nickgigliotos/multi-server ./server
  - docker build -t nickgigliotos/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push nickgigliotos/multi-client
  - docker push nickgigliotos/multi-nginx
  - docker push nickgigliotos/multi-server
  - docker push nickgigliotos/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-460644839126'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY